name: Check filter on branch creation
on:
  create:
jobs:
  EXEC:
    runs-on: ubuntu-latest
    if: startsWith('ref/heads/release/', github.ref)
    steps:
      - name: Echo branch name
        run: echo ${{ github.ref }}
